/**
 * Wiring check: run the plugin's `apply` against a recording stand-in for the
 * harness context and assert on what it registered.
 *
 * This runs offline and needs no profile install, so it catches the class of bug
 * that a syntax check cannot: a misspelled service, a tool whose schema the
 * harness would reject, a prompt section that never renders, or a guard hook
 * that misuses the waterfall contract.
 *
 * Run: node test/wiring.mjs
 */

import assert from 'node:assert/strict'

let passed = 0
let failed = 0

function check(name, fn) {
  try {
    fn()
    passed += 1
    console.log(`  ok   ${name}`)
  } catch (error) {
    failed += 1
    console.log(`  FAIL ${name}\n       ${error.message}`)
  }
}

/**
 * A minimal context that records registrations.
 *
 * Only the surface `apply` actually touches is modelled. Two details are
 * faithful on purpose, because both are load-bearing and easy to get wrong:
 *
 *   - `waterfall` semantics: `next` ignores its arguments and the decision
 *     travels by return value.
 *   - The settings contract: `installSection` hands the section's *resolved*
 *     value to `setSource`, so the row's own `config` (passed as the `base`
 *     layer) is part of what `source()` returns. A mock returning a bare `{}`
 *     would silently drop the row config and hide a real merge bug.
 */
function makeCtx(config, ConfigSchema) {
  const record = {
    tools: [],
    sections: [],
    hooks: [],
    commands: [],
    logs: [],
  }
  const ctx = {
    tools: { register: (definition) => { record.tools.push(definition); return () => {} } },
    systemPrompt: { section: (section) => { record.sections.push(section); return () => {} } },
    on: (event, listener) => { record.hooks.push({ event, listener }); return () => {} },
    inject: (services, callback) => {
      // The two optional services this plugin consumes.
      if (services.includes('settings')) {
        callback({
          settings: {
            installSection: (_owner, ns, schema, entry, hooks) => {
              record.settingsNs = ns
              record.settingsEntry = entry
              hooks.setSource(() => schema(entry ?? {}))
            },
          },
        })
      }
      if (services.includes('commands')) {
        callback({ commands: { register: (definition) => { record.commands.push(definition); return () => {} } } })
      }
      return () => {}
    },
    get: () => undefined,
    logger: { info: (m) => record.logs.push(m), warn: (m) => record.logs.push(String(m)) },
  }
  return { ctx, record }
}

/**
 * Assert one JSON Schema node stays inside the harness's supported subset.
 *
 * `isRoot` matters: the root `parameters` object is generated by the harness's
 * own compiler, which deliberately leaves it open and omits
 * `additionalProperties`. Every object a plugin author writes itself must state
 * that keyword explicitly — the compiler rejects an authored object without it.
 * @param node - the schema node.
 * @param path - where it sits, for the failure message.
 * @param isRoot - whether this is the harness-generated root parameter object.
 */
function assertSupportedSchema(node, path, isRoot = false) {
  const allowed = new Set([
    'type', 'properties', 'required', 'additionalProperties', 'items', 'enum', 'const',
    'oneOf', 'description', 'title', 'default', 'examples', 'deprecated', 'readOnly', 'writeOnly',
  ])
  if (typeof node !== 'object' || node === null) return
  for (const key of Object.keys(node)) {
    assert.ok(allowed.has(key), `${path}.${key} is not in the harness's supported keyword subset`)
  }
  if (node.type === 'object') {
    if (!isRoot) {
      assert.equal(typeof node.additionalProperties, 'boolean', `${path}.additionalProperties must be explicitly boolean when authored`)
    } else if (node.additionalProperties !== undefined) {
      assert.equal(typeof node.additionalProperties, 'boolean', `${path}.additionalProperties must be a boolean when present`)
    }
    for (const [key, child] of Object.entries(node.properties ?? {})) {
      assertSupportedSchema(child, `${path}.properties.${key}`)
    }
  }
  if (node.type === 'array' && node.items) assertSupportedSchema(node.items, `${path}.items`)
  if (Array.isArray(node.oneOf)) node.oneOf.forEach((b, i) => assertSupportedSchema(b, `${path}.oneOf[${i}]`))
}

console.log('apply wiring')

const { apply, name, inject, Config } = await import('../lib/index.js')
const { ctx, record } = makeCtx({}, Config)
apply(ctx, {})

check('registers under the expected plugin name', () => {
  assert.equal(name, 'dsh-typesafe')
})

check('declares the services it needs', () => {
  assert.deepEqual([...inject].sort(), ['systemPrompt', 'tools'])
})

check('the settings schema applies the shipped defaults to an empty row', () => {
  // Guards against a default drift between config.js and the schema: the row in
  // cordis.patch.yml omits keys, so every one of them must survive resolution.
  const resolved = Config({})
  assert.equal(resolved.model, 'jev-latest')
  assert.equal(resolved.inputPricePerMTok, 0.042)
  assert.equal(resolved.guardEnabled, true)
  assert.ok(Array.isArray(resolved.guardTools) && resolved.guardTools.length > 0)
})

check('registers exactly three tools', () => {
  assert.equal(record.tools.length, 3)
})

check('names the tools as documented', () => {
  assert.deepEqual(record.tools.map((t) => t.name).sort(), ['typesafe_decide', 'typesafe_route', 'typesafe_screen'])
})

check('every tool declares a non-empty description', () => {
  for (const tool of record.tools) {
    assert.ok(typeof tool.description === 'string' && tool.description.trim().length > 0, `${tool.name} has no description`)
  }
})

check('every tool declares the required output contract', () => {
  for (const tool of record.tools) {
    assert.ok(tool.output, `${tool.name} has no output`)
    assert.ok(tool.output.schema, `${tool.name} has no output.schema`)
    assert.equal(typeof tool.output.render, 'function', `${tool.name} has no output.render`)
  }
})

check('every tool schema stays in the supported subset', () => {
  for (const tool of record.tools) {
    assertSupportedSchema(tool.parameters, `${tool.name}.parameters`, true)
    assertSupportedSchema(tool.output.schema, `${tool.name}.output.schema`)
  }
})

check('every tool marks required parameters', () => {
  for (const tool of record.tools) {
    assert.ok(Array.isArray(tool.parameters.required) && tool.parameters.required.length > 0, `${tool.name} requires nothing`)
  }
})

check('registers one prompt section that renders guidance', () => {
  assert.equal(record.sections.length, 1)
  const text = record.sections[0].text()
  assert.ok(typeof text === 'string' && text.length > 0, 'prompt section rendered empty')
  assert.match(text, /decision model/)
})

check('the prompt section states a TRIGGER, not merely an available tool', () => {
  // The first field test failed because the section described an existence:
  // "You have Jev available through three tools". A passive fact does not fire
  // while the agent is mid-task. What fires is naming the act the agent is about
  // to perform itself — so the section must contain a stop-and-use instruction
  // tied to a recognizable behaviour.
  const text = record.sections[0].text()
  assert.match(text, /STOP AND USE IT|Before you\b/iu, 'no trigger phrase tied to a concrete action')
  assert.match(text, /keyword rules|regex|heuristics/iu, 'the keyword-rule trigger — the exact failure — is missing')
  assert.match(text, /classif|routing|scoring/iu, 'no recognition of the classification/scoring shape')
})

check('the prompt section forbids the two failure modes actually observed', () => {
  const text = record.sections[0].text()
  // (1) Hand-labels drift; (2) the agent asserts which items are uncertain
  // instead of reading confidence. Both happened in the field test.
  assert.match(text, /drift/iu, 'the label-drift warning is missing')
  assert.match(text, /confidence/iu, 'confidence guidance is missing')
  assert.match(text, /uncertain|not sure|ambiguous/iu, 'the uncertainty guidance is missing')
})

check('the prompt section keeps the batching rule explicit', () => {
  const text = record.sections[0].text()
  assert.match(text, /ONE call|Batch/iu, 'the batching rule — the whole cost advantage — is missing')
})

check('the prompt section renders empty when disabled', () => {
  const { ctx: ctx2, record: record2 } = makeCtx({ promptEnabled: false }, Config)
  apply(ctx2, { promptEnabled: false })
  assert.equal(record2.sections[0].text(), '')
})

check('the prompt section renders empty when the plugin is disabled', () => {
  const { ctx: ctx2, record: record2 } = makeCtx({ enabled: false }, Config)
  apply(ctx2, { enabled: false })
  assert.equal(record2.sections[0].text(), '')
})

check('the prompt section does not tell the agent to trust the guard blindly', () => {
  const text = record.sections[0].text()
  assert.match(text, /untrusted/iu)
  assert.doesNotMatch(text, /always trust/i)
})

check('the prompt section still names the tool boundaries honestly', () => {
  // Over-selling is the opposite failure: the section must keep saying what Jev
  // cannot do, or the agent will route reasoning work to it.
  const text = record.sections[0].text()
  assert.match(text, /multi-step reasoning|not this tool|cannot do/iu)
  assert.match(text, /never prose|never prose|no prose|not.*prose/iu)
})

check('the prompt section is placed in the behavioural-rule band', () => {
  // 700 sits between TEAM_POLICY (600) and PTC_ONLY (800). The shipped value was
  // 2750, which measured at offset 10653/17377 — mid-context, where instructions
  // are skimmed. A regression to a tool-catalogue order should fail here.
  const order = record.sections[0].order
  assert.ok(order < 1000, `prompt order ${order} places the rules after the tool catalogue`)
  assert.ok(order > 0, `prompt order ${order} places the rules before the persona`)
})

check('registers a tools/post-execute hook', () => {
  const guardHooks = record.hooks.filter((h) => h.event === 'tools/post-execute')
  assert.equal(guardHooks.length, 1)
})

check('registers a /typesafe command', () => {
  assert.equal(record.commands.length, 1)
  assert.equal(record.commands[0].name, 'typesafe')
})

check('registers the settings namespace', () => {
  assert.equal(record.settingsNs, 'typesafe')
})

console.log('\nguard hook contract')

const hook = record.hooks.find((h) => h.event === 'tools/post-execute').listener

check('passes a non-guarded tool through by returning the chain decision', async () => {
  const decision = { kind: 'accept' }
  const returned = await hook(
    { name: 'read', signal: undefined },
    { isError: false, content: [{ type: 'text', text: 'x'.repeat(500) }] },
    async () => decision,
  )
  assert.equal(returned, decision, 'an unscreened tool must return the untouched decision')
})

check('passes an errored result through untouched', async () => {
  const decision = { kind: 'accept' }
  const returned = await hook(
    { name: 'web_fetch', signal: undefined },
    { isError: true, content: [{ type: 'text', text: 'Error: boom' }] },
    async () => decision,
  )
  assert.equal(returned, decision)
})

check('does not override a block decided earlier in the chain', async () => {
  const blocked = { kind: 'block', feedback: [{ type: 'text', text: 'denied' }] }
  const returned = await hook(
    { name: 'web_fetch', signal: undefined },
    { isError: false, content: [{ type: 'text', text: 'x'.repeat(500) }] },
    async () => blocked,
  )
  assert.equal(returned, blocked, 'a blocking decision must survive the guard')
})

check('annotates a guarded result when the key is absent (fail-open)', async () => {
  // No credential service and no environment key: the screen cannot run, and the
  // hook must still annotate rather than silently pass.
  const returned = await hook(
    { name: 'web_fetch', signal: undefined },
    { isError: false, content: [{ type: 'text', text: 'y'.repeat(500) }] },
    async () => ({ kind: 'accept' }),
  )
  assert.equal(returned.kind, 'accept')
  assert.ok(Array.isArray(returned.content))
  assert.equal(returned.content.length, 2, 'expected a notice plus the original content')
  assert.match(returned.content[0].text, /TypeSafe guard/)
  assert.match(returned.content[0].text, /Not screened/)
  assert.equal(returned.content[1].text, 'y'.repeat(500), 'the original content must survive intact')
})

check('does not screen when the guard is disabled', async () => {
  const cfg = { guardEnabled: false }
  const { ctx: ctx2, record: record2 } = makeCtx(cfg, Config)
  apply(ctx2, cfg)
  const hook2 = record2.hooks.find((h) => h.event === 'tools/post-execute').listener
  const decision = { kind: 'accept' }
  const returned = await hook2(
    { name: 'web_fetch', signal: undefined },
    { isError: false, content: [{ type: 'text', text: 'z'.repeat(500) }] },
    async () => decision,
  )
  assert.equal(returned, decision)
})

check('skips content below the minimum length', async () => {
  const decision = { kind: 'accept' }
  const returned = await hook(
    { name: 'web_fetch', signal: undefined },
    { isError: false, content: [{ type: 'text', text: 'short' }] },
    async () => decision,
  )
  assert.equal(returned, decision, 'short content must not spend a request')
})

console.log('\n/ttypesafe command')

const command = record.commands[0]

check('the command handler returns a success result', async () => {
  const result = await command.handler({})
  assert.equal(result.kind, 'success')
  assert.match(result.text, /TypeSafe Jev/)
})

check('the command reports the unconfigured state honestly', async () => {
  const result = await command.handler({})
  assert.match(result.text, /NO API KEY CONFIGURED/)
})

check('the command reports the price and the guard state', async () => {
  const result = await command.handler({})
  assert.match(result.text, /0\.042/)
  assert.match(result.text, /guard: on/)
})

console.log(`\n${passed} passed, ${failed} failed`)
process.exit(failed === 0 ? 0 : 1)
